"""
analyzer.py – AI text detection via Ollama (local LLM)

Uses mistral:7b running locally through Ollama.
No API key or internet connection required.

Requirements:
    1. Install Ollama: https://ollama.com
    2. Pull the model: ollama pull mistral:7b
    3. Ollama runs automatically as a background service

Ollama API runs on http://localhost:11434 by default.
"""

import json
import re
import urllib.request
import urllib.error

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "mistral:7b"


PROMPT_TEMPLATE = """You are an expert AI-content detection system. Analyze the following text and determine the likelihood it was generated by an LLM (ChatGPT, Claude, Gemini, etc.).

Indicators of AI-generated text:
- Overly uniform sentence structure and length
- Lack of personal voice or idiosyncratic phrasing
- Excessive hedging ("it's worth noting", "in conclusion", "it is important to")
- Perfect logical flow with little tangential thinking
- Formal or encyclopedic tone even in casual contexts
- Absence of grammatical imperfections or natural disfluencies
- Balanced, non-committal positions; overuse of transitions ("Furthermore", "Additionally")

Indicators of human-written text:
- Personal opinions stated directly and confidently
- Informal language, contractions, slang, digressions
- Idiosyncratic word choices; first-hand specific details
- Natural inconsistencies in tone or register
- Grammatical imperfections or unconventional punctuation

TEXT TO ANALYZE:
---
{text}
---

Respond with ONLY a valid JSON object — no preamble, no markdown fences, no explanation outside the JSON:
{{
  "overall_score": <float 0.0-1.0>,
  "overall_label": "<Likely Human|Possibly AI|Likely AI>",
  "reasoning": "<2-4 sentence explanation of key signals detected>",
  "sentences": [
    {{
      "text": "<sentence text>",
      "score": <float 0.0-1.0>,
      "signal": "<brief reason for this sentence's score>"
    }}
  ]
}}

Rules:
- overall_score: 0.0 = definitely human, 1.0 = definitely AI
- Analyze up to 10 representative sentences
- overall_label must match overall_score:
    Likely Human  = 0.00–0.44
    Possibly AI   = 0.45–0.74
    Likely AI     = 0.75–1.00
- Output ONLY the JSON object, nothing else"""


def check_ollama() -> tuple[bool, str]:
    """Check if Ollama is running and the model is available."""
    try:
        req = urllib.request.Request("http://localhost:11434/api/tags")
        with urllib.request.urlopen(req, timeout=3) as resp:
            data = json.loads(resp.read())
            models = [m["name"] for m in data.get("models", [])]
            # Check for model (may be listed as "mistral:7b" or "mistral")
            available = any(MODEL.split(":")[0] in m for m in models)
            if not available:
                return False, (
                    f"Model '{MODEL}' not found. Run: ollama pull {MODEL}\n"
                    f"Available models: {', '.join(models) or 'none'}"
                )
            return True, "ok"
    except urllib.error.URLError:
        return False, (
            "Ollama is not running. Start it with: ollama serve\n"
            "Install from: https://ollama.com"
        )
    except Exception as e:
        return False, f"Ollama check failed: {e}"


def analyze_text(text: str, context: str = "auto") -> dict:
    """
    Analyze text for AI-generation likelihood using local Ollama/Mistral.

    Returns a dict with:
        overall_score: float 0.0-1.0
        overall_label: str
        reasoning: str
        sentences: list of {text, score, signal}
    """
    # Quick Ollama availability check
    ok, msg = check_ollama()
    if not ok:
        raise ValueError(msg)

    prompt = PROMPT_TEMPLATE.format(text=text[:6000])  # Mistral 7b context limit safety

    payload = json.dumps({
        "model": MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.1,      # Low temp for consistent, deterministic scoring
            "top_p": 0.9,
            "num_predict": 1200,     # Max tokens to generate
        }
    }).encode("utf-8")

    req = urllib.request.Request(
        OLLAMA_URL,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())
    except urllib.error.URLError as e:
        raise ValueError(f"Could not reach Ollama at {OLLAMA_URL}: {e}")
    except TimeoutError:
        raise ValueError("Ollama timed out. The model may still be loading — try again in a moment.")

    raw = data.get("response", "").strip()

    # Strip markdown code fences if the model added them anyway
    raw = re.sub(r'^```(?:json)?\s*', '', raw, flags=re.MULTILINE)
    raw = re.sub(r'\s*```\s*$', '', raw, flags=re.MULTILINE)
    raw = raw.strip()

    # Extract first JSON object if there's surrounding text
    json_match = re.search(r'\{[\s\S]*\}', raw)
    if json_match:
        raw = json_match.group(0)

    try:
        result = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"Model returned invalid JSON: {e}\n"
            f"Raw output (first 300 chars): {raw[:300]}"
        )

    # Validate and normalize overall_score
    result["overall_score"] = max(0.0, min(1.0, float(result.get("overall_score", 0.5))))
    score = result["overall_score"]

    # Force label to match score (model sometimes gets this wrong)
    if score >= 0.75:
        result["overall_label"] = "Likely AI"
    elif score >= 0.45:
        result["overall_label"] = "Possibly AI"
    else:
        result["overall_label"] = "Likely Human"

    result["reasoning"] = str(result.get("reasoning", "No reasoning provided."))

    # Normalize sentence scores
    sentences = result.get("sentences", [])
    for s in sentences:
        s["score"] = max(0.0, min(1.0, float(s.get("score", 0.5))))
    result["sentences"] = sentences[:10]

    return result
